### ISSUE TITLE
推荐宾语生成的其他项目可供参考

### ISSUE THREAD

**Issue by exgcdwu** [Delta-Water/RustedWarfare-Development-Tools#1]
宾语生成python库:
https://github.com/exgcdwu/Rusted-Warfare-map-editor-for-city-occupation-play-
宾语生成java组件:
https://github.com/n9tank/rwtmxJava

**Comment by Delta-Water** [comment]
收到。
或许你也可以做一个cpp版本的本应用呢？😋
我最近有空会写项目介绍文件，用以替换知乎上的教程。
